# SVM

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import svm
import seaborn as sns

In [2]:
X_train = np.asarray(pd.read_csv("training_data.csv"))
y_train = np.asarray(pd.read_csv("training_label.csv"))
X_test = np.asarray(pd.read_csv("testing_data.csv"))
y_test = np.asarray(pd.read_csv("testing_label.csv"))

In [3]:
n_train = X_train.shape[0]
n_test = X_test.shape[0]

In [4]:
def z_score(x, axis):
    xr = np.rollaxis(x, axis=axis)
    xr -= np.mean(x, axis=axis)
    xr /= np.std(x, axis=axis)
    # print(x)
    return x

In [5]:
X_train = z_score(X_train,0)
X_test = z_score(X_test,0)

In [6]:
from keras.models import Sequential
from keras.utils import np_utils
from keras.layers.core import Dense, Activation, Dropout

Using TensorFlow backend.


## svc

In [7]:
svc = svm.SVC(kernel='rbf',gamma='auto')
svc.fit(X_train, y_train)

c:\users\50221\appdata\local\programs\python\python37\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


SVC(gamma='auto')

In [8]:
y_train_pred = svc.predict(X_train)
y_train_pred = y_train_pred.reshape(y_train_pred.shape[0],1)
error_vec = [0 if k[0]==k[1] else 1 for k in np.hstack((y_train, y_train_pred))]
err_rate = sum(error_vec)/len(y_train)
print("Training Accuracy:", (1- err_rate)*100, "%")

Training Accuracy: 68.50828729281768 %


In [9]:
print(np.hstack((y_train, y_train_pred)))

[[-1. -1.]
 [ 1. -1.]
 [ 1. -1.]
 [-1. -1.]
 [-1. -1.]
 [ 1. -1.]
 [-1. -1.]
 [ 1.  1.]
 [-1. -1.]
 [ 1. -1.]
 [ 1.  1.]
 [ 1. -1.]
 [ 1.  1.]
 [-1. -1.]
 [-1.  1.]
 [ 1.  1.]
 [-1. -1.]
 [ 1. -1.]
 [ 1. -1.]
 [-1. -1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1. -1.]
 [ 1. -1.]
 [-1. -1.]
 [ 1. -1.]
 [-1.  1.]
 [ 1. -1.]
 [ 1.  1.]
 [-1. -1.]
 [ 1. -1.]
 [-1.  1.]
 [ 1.  1.]
 [-1. -1.]
 [-1. -1.]
 [-1. -1.]
 [-1. -1.]
 [-1. -1.]
 [ 1.  1.]
 [ 1.  1.]
 [-1.  1.]
 [ 1. -1.]
 [ 1.  1.]
 [ 1. -1.]
 [ 1. -1.]
 [-1. -1.]
 [ 1.  1.]
 [-1. -1.]
 [-1. -1.]
 [-1. -1.]
 [ 1.  1.]
 [-1. -1.]
 [-1.  1.]
 [ 1. -1.]
 [-1. -1.]
 [-1.  1.]
 [-1. -1.]
 [ 1.  1.]
 [-1.  1.]
 [-1. -1.]
 [ 1.  1.]
 [-1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1. -1.]
 [-1. -1.]
 [ 1. -1.]
 [-1. -1.]
 [ 1. -1.]
 [ 1.  1.]
 [ 1.  1.]
 [-1. -1.]
 [-1.  1.]
 [-1. -1.]
 [ 1.  1.]
 [-1. -1.]
 [-1. -1.]
 [ 1.  1.]
 [-1. -1.]
 [-1. -1.]
 [-1. -1.]
 [-1. -1.]
 [-1. -1.]
 [-1. -1.]
 [-1. -1.]
 [ 1. -1.]
 [ 1.  1.]
 [-1. -1.]
 [-1. -1.]
 [ 1.  1.]
 [ 1. -1.]

In [10]:
Sq_err_vec = [ (it[0]-it[1])**2 for it in np.hstack((y_train, y_train_pred))]
sq_err = sum(Sq_err_vec)/len(y_train)
print("Training square error:",sq_err)

Training square error: 1.2596685082872927


In [11]:
y_test_pred = svc.predict(X_test)
y_test_pred = y_test_pred.reshape(y_test_pred.shape[0],1)
test_error_vec = [0 if k[0]==k[1] else 1 for k in np.hstack((y_test, y_test_pred))]
test_err_rate = sum(test_error_vec)/len(y_test)
print("Testing Accuracy:", (1- test_err_rate)*100, "%")

Testing Accuracy: 52.25806451612903 %


In [12]:
test_Sq_err_vec = [ (it[0]-it[1])**2 for it in np.hstack((y_test, y_test_pred))]
test_sq_err = sum(test_Sq_err_vec)/len(y_test)
print("Testing square error:",test_sq_err)

Testing square error: 1.9096774193548387


## linear SVC

In [13]:
lin_svc = svm.LinearSVC()
lin_svc.fit(X_train, y_train)

c:\users\50221\appdata\local\programs\python\python37\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


LinearSVC()

In [14]:
y_train_pred = lin_svc.predict(X_train)
y_train_pred = y_train_pred.reshape(y_train_pred.shape[0],1)
error_vec = [0 if k[0]==k[1] else 1 for k in np.hstack((y_train, y_train_pred))]
err_rate = sum(error_vec)/len(y_train)
print("Training Accuracy:", (1- err_rate)*100, "%")

Training Accuracy: 58.011049723756905 %


In [15]:
Sq_err_vec = [ (it[0]-it[1])**2 for it in np.hstack((y_train, y_train_pred))]
sq_err = sum(Sq_err_vec)/len(y_train)
print("Training square error:",sq_err)

Training square error: 1.6795580110497237


In [16]:
y_test_pred = lin_svc.predict(X_test)
y_test_pred = y_test_pred.reshape(y_test_pred.shape[0],1)
test_error_vec = [0 if k[0]==k[1] else 1 for k in np.hstack((y_test, y_test_pred))]
test_err_rate = sum(test_error_vec)/len(y_test)
print("Testing Accuracy:", (1- test_err_rate)*100, "%")

Testing Accuracy: 50.96774193548388 %


In [17]:
test_Sq_err_vec = [ (it[0]-it[1])**2 for it in np.hstack((y_test, y_test_pred))]
test_sq_err = sum(test_Sq_err_vec)/len(y_test)
print("Testing square error:",test_sq_err)

Testing square error: 1.961290322580645


# Feature selection 

In [18]:
features_selected = ["month","DMC","DC","RH","wind"]

In [19]:
X_train1 = pd.read_csv("training_data.csv")[features_selected]
y_train1 = pd.read_csv("training_label.csv")
X_test1 = pd.read_csv("testing_data.csv")[features_selected]
y_test1 = pd.read_csv("testing_label.csv")

In [20]:
X_tr1 = np.asarray(X_train1)
y_tr1 = np.asarray(y_train1)
X_te1 = np.asarray(X_test1)
y_te1 = np.asarray(y_test1)

In [21]:
X_tr1 = z_score(X_tr1,0)
X_te1 = z_score(X_te1,0)

In [22]:
svc = svm.SVC(kernel='rbf',gamma='auto')
svc.fit(X_tr1, y_tr1)

c:\users\50221\appdata\local\programs\python\python37\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


SVC(gamma='auto')

In [25]:
y_train_pred1 = svc.predict(X_tr1)
y_train_pred1 = y_train_pred.reshape(y_train_pred1.shape[0],1)
error_vec1 = [0 if k[0]==k[1] else 1 for k in np.hstack((y_tr1, y_train_pred1))]
err_rate1 = sum(error_vec1)/len(y_tr1)
print("Training Accuracy:", (1- err_rate1)*100, "%")

Training Accuracy: 58.011049723756905 %


In [26]:
Sq_err_vec = [ (it[0]-it[1])**2 for it in np.hstack((y_tr1, y_train_pred1))]
sq_err = sum(Sq_err_vec)/len(y_tr1)
print("Training square error:",sq_err)

Training square error: 1.6795580110497237


In [27]:
y_test_pred = svc.predict(X_te1)
y_test_pred = y_test_pred.reshape(y_test_pred.shape[0],1)
test_error_vec = [0 if k[0]==k[1] else 1 for k in np.hstack((y_te1, y_test_pred))]
test_err_rate = sum(test_error_vec)/len(y_te1)
print("Testing Accuracy:", (1- test_err_rate)*100, "%")

Testing Accuracy: 48.38709677419355 %


In [28]:
test_Sq_err_vec = [ (it[0]-it[1])**2 for it in np.hstack((y_te1, y_test_pred))]
test_sq_err = sum(test_Sq_err_vec)/len(y_te1)
print("Testing square error:",test_sq_err)

Testing square error: 2.064516129032258


# K-fold validation 

In [41]:
n_train = len(X_train)

k_fold = 5
id_train = [[]] * k_fold
id_val = [[]] * k_fold

for m in range(k_fold):
    id_val[m] = range(m, n_train, k_fold) # Indices of k_fold validation sets.
    id_train[m] = np.setdiff1d(range(n_train), id_val[m])

In [42]:
CMat_train_best = None
CMat_val_best = None
acc_train_best = 0
acc_val_best = 0
model_best = None
Val_acc = []

In [55]:
from sklearn.metrics import confusion_matrix
# ConfusionMatrix = np.zeros((2,2), dtype=int)

for m in range(k_fold):
    print("\n iteration", m)
    X_train_cur = X_train[id_train[m]]
    y_train_cur = y_train[id_train[m]]
    X_val_cur = X_train[id_val[m]]
    y_val_cur = y_train[id_val[m]]

    svc_cur = svm.SVC(kernel='rbf',gamma='auto')
    svc_cur.fit(X_train_cur, y_train_cur)
    y_pred_train_cur = svc_cur.predict(X_train_cur)
    y_pred_val_cur = svc_cur.predict(X_val_cur)
    
    CMat_train = confusion_matrix(y_train_cur, y_pred_train_cur, labels=[-1,1])
    acc_train = np.sum(np.diag(CMat_train))/np.shape(X_train_cur)[0]
    
    CMat_val = confusion_matrix(y_val_cur, y_pred_val_cur, labels=[-1,1])
    acc_val = np.sum(np.diag(CMat_val))/np.shape(X_val_cur)[0]
    Val_acc.append(acc_val)
    
    if acc_val > acc_val_best:
        acc_train_best = acc_train
        acc_val_best = acc_val
        model_best =  svc_cur
        CMat_train_best = CMat_train
        CMat_val_best = CMat_val
    
    print("Training confusion matrix:\n", CMat_train)
    print("Training accuracy:", acc_train)
    print("Validation confusion matrix:\n", CMat_val)
    print("Validation accuracy:", acc_val)


 iteration 0
Training confusion matrix:
 [[132  26]
 [ 78  53]]
Training accuracy: 0.6401384083044983
Validation confusion matrix:
 [[26  7]
 [28 12]]
Validation accuracy: 0.5205479452054794

 iteration 1
Training confusion matrix:
 [[116  34]
 [ 60  79]]
Training accuracy: 0.6747404844290658
Validation confusion matrix:
 [[28 13]
 [15 17]]
Validation accuracy: 0.6164383561643836

 iteration 2
Training confusion matrix:
 [[123  33]
 [ 56  78]]
Training accuracy: 0.6931034482758621
Validation confusion matrix:
 [[20 15]
 [24 13]]
Validation accuracy: 0.4583333333333333

 iteration 3
Training confusion matrix:
 [[ 98  55]
 [ 35 102]]
Training accuracy: 0.6896551724137931
Validation confusion matrix:
 [[18 20]
 [20 14]]
Validation accuracy: 0.4444444444444444

 iteration 4
Training confusion matrix:
 [[ 99  48]
 [ 39 104]]
Training accuracy: 0.7
Validation confusion matrix:
 [[16 28]
 [11 17]]
Validation accuracy: 0.4583333333333333


c:\users\50221\appdata\local\programs\python\python37\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
c:\users\50221\appdata\local\programs\python\python37\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
c:\users\50221\appdata\local\programs\python\python37\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
c:\users\50221\appdata\local\programs\python\python37\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed w

In [56]:
print("Highest training accuracy:", acc_train_best)
print("Best training confusion matrix:\n", CMat_train_best)
print("Highest validation accuracy:", acc_val_best)
print("Best validation confusion matrix:\n", CMat_val_best)
print(model_best)

Highest training accuracy: 0.6747404844290658
Best training confusion matrix:
 [[116  34]
 [ 60  79]]
Highest validation accuracy: 0.6164383561643836
Best validation confusion matrix:
 [[28 13]
 [15 17]]
SVC(gamma='auto')


In [58]:
y_test_pred = model_best.predict(X_test)
y_test_pred = y_test_pred.reshape(y_test_pred.shape[0],1)
test_error_vec = [0 if k[0]==k[1] else 1 for k in np.hstack((y_test, y_test_pred))]
test_err_rate = sum(test_error_vec)/len(y_test)
print("Testing Accuracy:", (1-test_err_rate)*100, "%")

Testing Accuracy: 49.032258064516135 %


In [59]:
test_Sq_err_vec = [ (it[0]-it[1])**2 for it in np.hstack((y_test, y_test_pred))]
test_sq_err = sum(test_Sq_err_vec)/len(y_test)
print("Testing square error:",test_sq_err)

Testing square error: 2.0387096774193547
